version: '2.1'
  networks:
    ca:
      name: ca_network
  services:
    ca.org3.com:
      image: hyperledger/fabric-ca:1.5.6
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.org3.com
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_PORT=3054
        - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:13054
      ports:
        - "3054:3054"
        - "13054:13054"
      command: sh -c 'fabric-ca-server start -d'
      volumes:
        - ./config/org3.com/ca:/etc/hyperledger/fabric-ca-server
      container_name: ca.org3.com
      hostname: ca.org3.com
      networks:
        - ca

    tls.org3.com:
      image: hyperledger/fabric-ca:1.5.6
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=tls.org3.com
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_PORT=3354
        - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:13354
      ports:
        - "3154:3354"
        - "13154:13354"
      command: sh -c 'fabric-ca-server start -d'
      volumes:
        - ./config/org3.com/tls:/etc/hyperledger/fabric-ca-server
      container_name: tls.org3.com
      hostname: tls.org3.com
      networks:
        - ca
