  version: '2.1'
  networks:
    ca:
      name: ca_network
  services:
    ca.org1.com:
      image: hyperledger/fabric-ca:1.5.6
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.org1.com
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_PORT=1054
        - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:11054
      ports:
        - "1054:1054"
        - "11054:11054"
      command: sh -c 'fabric-ca-server start -d'
      volumes:
        - ./config/org1.com/ca:/etc/hyperledger/fabric-ca-server
      container_name: ca.org1.com
      hostname: ca.org1.com
      networks:
        - ca

    tls.org1.com:
      image: hyperledger/fabric-ca:1.5.6
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=tls.org1.com
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_PORT=1154
        - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:11154
      ports:
        - "1154:1154"
        - "11154:11154"
      command: sh -c 'fabric-ca-server start -d'
      volumes:
        - ./config/org1.com/tls:/etc/hyperledger/fabric-ca-server
      container_name: tls.org1.com
      hostname: tls.org1.com
      networks:
        - ca

    ca.org2.com:
      image: hyperledger/fabric-ca:1.5.6
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.org2.com
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_PORT=2054
        - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:12054
      ports:
        - "2054:2054"
        - "12054:12054"
      command: sh -c 'fabric-ca-server start -d'
      volumes:
        - ./config/org2.com/ca:/etc/hyperledger/fabric-ca-server
      container_name: ca.org2.com
      hostname: ca.org2.com
      networks:
        - ca

    tls.org2.com:
      image: hyperledger/fabric-ca:1.5.6
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=tls.org2.com
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_PORT=2154
        - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:12154
      ports:
        - "2154:2154"
        - "12154:12154"
      command: sh -c 'fabric-ca-server start -d'
      volumes:
        - ./config/org2.com/tls:/etc/hyperledger/fabric-ca-server
      container_name: tls.org2.com
      hostname: tls.org2.com
      networks:
        - ca

    ca.org4.com:
      image: hyperledger/fabric-ca:1.5.6
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=ca.org4.com
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_PORT=4054
        - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:14054
      ports:
        - "4054:4054"
        - "14054:14054"
      command: sh -c 'fabric-ca-server start -d'
      volumes:
        - ./config/org4.com/ca:/etc/hyperledger/fabric-ca-server
      container_name: ca.org4.com
      hostname: ca.org4.com
      networks:
        - ca

    tls.org4.com:
      image: hyperledger/fabric-ca:1.5.6
      environment:
        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
        - FABRIC_CA_SERVER_CA_NAME=tls.org4.com
        - FABRIC_CA_SERVER_TLS_ENABLED=true
        - FABRIC_CA_SERVER_PORT=4154
        - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:14154
      ports:
        - "4154:4154"
        - "14154:14154"
      command: sh -c 'fabric-ca-server start -d'
      volumes:
        - ./config/org4.com/tls:/etc/hyperledger/fabric-ca-server
      container_name: tls.org4.com
      hostname: tls.org4.com
      networks:
        - ca
